services:
  - type: web
    name: huffman-compression
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000 --workers 3 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
